version: '3'

services:
  movies-api:
    ports:
      - 8080:8080

  movies-web:
    build: ./client
    container_name: movies-web
    env_file: ./client/.env
    ports:
      - 3000:80
    links:
      - movies-api
    environment:
      REACT_APP_API_URL: ${REACT_APP_API_URL}
  postgres:
    image: 'postgres:14.5'
    restart: always
    env_file: ./server/.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: movies
    logging:
      options:
        max-size: 10m
        max-file: '3'
    ports:
      - '5432:5432'
    volumes:
      - ./server/postgres-data:/var/lib/postgresql/data
      - ./server/sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
